modLoader = "javafml"
loaderVersion = "[36,)"
license = "CC BY 4.0"

[[mods]]
modId = "londonundergroundtrains"
version = "@version@"
displayName = "MTR London Underground Trains"
authors = "ExtremeMakerX"
description = "A London Underground Addon for the Minecraft Transit Railway Mod"
logoFile = "icon.png"

[[dependencies.londonundergroundtrains]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.londonundergroundtrains]]
modId = "minecraft"
mandatory = true
versionRange = "[@minecraft@]"
ordering = "NONE"
side = "BOTH"

[[dependencies.londonundergroundtrains]]
modId = "mtr"
mandatory = true
ordering = "AFTER"
side = "BOTH"